language: node_js
node_js:
  - "8"
install:
  - wget -O apex https://github.com/apex/apex/releases/download/v0.16.0/apex_linux_amd64
  - cd functions/optimize
  - npm install
  - cd ../../
  - chmod +x apex
script: true
after_success: export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_REGION=$AWS_REGION && ./apex deploy